name: CI

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
      - "!.github/workflows/ci.yml"
  push:
    branches:
      - main
      - "renovate/**"
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
      - "!.github/workflows/ci.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - node: 22.11.0
          - node: 8.17.0
          # Numerous things break in lower versions of node.
          # - node: 4.9.1
          # - node: 0.12.18
          # - node: 0.10.48
    steps:
      - uses: taiki-e/checkout-action@v1

      - uses: pnpm/action-setup@v4.0.0

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm run init

      - run: curl -L -o node.tar.gz "https://nodejs.org/dist/v${{ matrix.node }}/node-v${{ matrix.node }}-linux-x64.tar.gz"

      - run: tar -zxf node.tar.gz

      - run: ./node-v${{ matrix.node }}-linux-x64/bin/node --version

      - run: TARGET=node${{ matrix.node }} ./ci.sh ./node-v${{ matrix.node }}-linux-x64/bin/node
